# Generated by Django 4.2.2 on 2023-07-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_secretcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretCode',
        ),
    ]
